### PR TITLE
Run CI on Julia 1.5 and 1.6

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by chriselrod** [comment]
I'm going to have to take a look at those errors.

**Comment by DilumAluthge** [comment]
Out of curiosity, do you think the bugs are in Gaius, or in LoopVectorization/VectorizationBase? Or both?

**Comment by chriselrod** [comment]
I'll look at this later today.

From the log, one of the bugs looks like it's in LoopVectorization's reading of a stridedpointer.
But it could be that an invalid stridedpointer is getting generated somewhere.

**Comment by chriselrod** [comment]
Tests pass locally on LoopVectorization 0.9.8 (which requires VectorizationBase 0.14).

**Comment by chriselrod** [comment]
Great: tests pass.

Thanks for your CI updates.

I'll let you mark it as ready before merging.

**Pull request merged**
