### PR TITLE
Transition from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by DilumAluthge**
I know you're not actively working on this package, but I figured that it would be good to have working CI, in case someone else wants to make use of some of the code.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
I tested this on my fork and all checks passed: https://github.com/DilumAluthge/Gaius.jl/pull/1

**Comment by DilumAluthge** [comment]
@MasonProtter Would you be willing to merge this?

**Comment by chriselrod** [comment]
If we want this library to work on Julia 1.6, I (or someone else) will have to update to VectorizationBase 0.13.

**Comment by MasonProtter** [comment]
Thanks @DilumAluthge! 

> If we want this library to work on Julia 1.6, I (or someone else) will have to update to VectorizationBase 0.13.

> I assume you tested and found that version broke something?

I don't really remember, it's been a while, but I tried just updating everything and running the test suite and got a segfault.

**Pull request merged**
