### PR TITLE
Remove PtrMatrix, add LV 0.12 support

### PR DESCRIPTION
**Pull request by chriselrod**
As of Julia 1.5, using PtrMatrix to avoid allocations shouldn't be necessary.

### CODE REVIEW

**Comment by chriselrod** [comment]
My primary motivation for getting rid of it is to reduce the maintenance burden.
Something broke with them, and if it's easier to remove than debug...

**Comment by DilumAluthge** [comment]
I like it! But it would be good to fix the test failures first.

I imagine that most (if not all) test failures are the same as the failures in https://github.com/JuliaSIMD/LoopVectorization.jl/pull/218

**Comment by chriselrod** [comment]
Not all, but a couple.
Working on those now.

**Comment by chriselrod** [comment]
@DilumAluthge all tests pass.

**Pull request merged**
