### PR TITLE
[DO NOT MERGE] Test on macOS (in addition to Linux and Windows)

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@chriselrod What do you think about these failures on macOS? E.g. in the `Int64 Matrix-Matrix ` testset.

I ran the tests locally on my MacBook, and all the tests passed. My MacBook is quite old, and I don't think my CPU supports AVX512, so maybe that's the difference?

I'll post the logs from running the tests locally so you can compare my logs to the logs from CI.

**Comment by DilumAluthge** [comment]
<details>

<summary>Here are the logs from running locally on my Mac: (click to expand)</summary>

```
(@v1.7) pkg> test Gaius
     Testing Gaius
Status `/private/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_omBQxk/Project.toml`
  [6e4b80f9] BenchmarkTools v0.5.0
  [bffe22d1] Gaius v0.3.1-DEV `~/Downloads/Gaius.jl`
  [bdcacae8] LoopVectorization v0.9.8
  [09ab397b] StructArrays v0.4.4
  [c4a57d5a] UnsafeArrays v1.0.1
  [3d5dd08c] VectorizationBase v0.14.3
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [9a3f8284] Random `@stdlib/Random`
  [8dfed614] Test `@stdlib/Test`
Status `/private/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_omBQxk/Manifest.toml`
  [79e6a3ab] Adapt v2.3.0
  [4fba245c] ArrayInterface v2.14.6
  [6e4b80f9] BenchmarkTools v0.5.0
  [9a962f9c] DataAPI v1.4.0
  [e2d170a0] DataValueInterfaces v1.0.0
  [ffbed154] DocStringExtensions v0.8.3
  [bffe22d1] Gaius v0.3.1-DEV `~/Downloads/Gaius.jl`
  [0e44f5e4] Hwloc v1.1.0
  [615f187c] IfElse v0.1.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [682c06a0] JSON v0.21.1
  [bdcacae8] LoopVectorization v0.9.8
  [6fe1bfb0] OffsetArrays v1.4.1
  [69de0a69] Parsers v1.0.15
  [ae029012] Requires v1.1.2
  [476501e8] SLEEFPirates v0.6.1
  [09ab397b] StructArrays v0.4.4
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v1.2.2
  [3a884ed6] UnPack v1.0.2
  [c4a57d5a] UnsafeArrays v1.0.1
  [3d5dd08c] VectorizationBase v0.14.3
  [e33a78d0] Hwloc_jll v2.2.0+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
     Testing Running tests...
Julia Version 1.7.0-DEV.129
Commit 188755071f (2020-12-19 18:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin20.2.0)
  uname: Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz:
              speed         user         nice          sys         idle          irq
       #1  2600 MHz      16939 s          0 s       7465 s      15871 s          0 s
       #2  2600 MHz       8257 s          0 s       3431 s      28583 s          0 s
       #3  2600 MHz      18488 s          0 s       6726 s      15057 s          0 s
       #4  2600 MHz       7815 s          0 s       3275 s      29181 s          0 s

  Memory: 8.0 GB (1185.734375 MB free)
  Uptime: 4026.0 sec
  Load Avg:  3.8798828125  5.6953125  5.64111328125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, haswell)
Environment:
  JULIA_PKG_SERVER =
  JULIA_LOAD_PATH = @:/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_omBQxk
  TERM = xterm-256color
  PATH = /Users/dilum/bin:/Users/dilum/.cargo/bin:/Users/dilum/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin
  XPC_FLAGS = 0x0
  HOME = /Users/dilum
  R_HOME = *
  JULIA_LOAD_PATH = @:/var/folders/jy/7hh5zyw95cg2lh66lfpthqq80000gn/T/jl_omBQxk
Test Summary:                | Pass  Total
Float64 Matrix-Vector        |   24     24
Test Summary:                | Pass  Total
ComplexF64  Matrix-Vector    |   24     24
Test Summary:                | Pass  Total
Float32 Matrix-Vector        |   24     24
Test Summary:                | Pass  Total
Int64 Matrix-Vector          |   24     24
Test Summary:                | Pass  Total
ComplexInt32 Matrix-Vector   |   24     24
Test Summary:                | Pass  Total
Float64 CoVector-Matrix      |   48     48
Test Summary:                | Pass  Total
ComplexF32 CoVector-Matrix   |   48     48
Test Summary:                | Pass  Total
ComplexFloat64 Matrix-Matrix |   24     24
Test Summary:                | Pass  Total
Float64 Matrix-Matrix        |   60     60
Test Summary:                | Pass  Total
Float32 Matrix-Matrix        |   30     30
Test Summary:                | Pass  Total
Int64 Matrix-Matrix          |   30     30
Test Summary:                | Pass  Total
Int32 Matrix-Matrix          |   30     30
     Testing Gaius tests passed
```

</details>

**Comment by chriselrod** [comment]
More likely the Macs don't support AVX2.

**Comment by chriselrod** [comment]
Yeah, if you look at the logs, this is the Mac CPU:
https://ark.intel.com/content/www/us/en/ark/products/64601/intel-xeon-processor-e5-1650-12m-cache-3-20-ghz-0-0-gt-s-intel-qpi.html
No AVX2.

**Comment by chriselrod** [comment]
Interestingly, all three failures were with `Int64`, `A' * B'`.
I should probably setup a computer to pretend to be ivybridge to actually diagnose these things.

**Comment by DilumAluthge** [comment]
Ideally, if AVX2 is not supported, we would fall back to a slow path that gives the correct answer.

**Comment by chriselrod** [comment]
Currently, it is lack of AVX2 that causes problems with integers.

I'm trying to support it, and you'll see that most things work, but something is going wrong somewhere.

This looks extremely familiar:
```julia
 (1000 × 1002) × (1002 × 1000): Test Failed at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:205
  Expression: blocked_mul!(C1, At', Bt') ≈ C2
   Evaluated: [319107 -119424 … 9223372036854775807 9223372036854775807; 16347 -364528 … 9223372036854775807 9223372036854775807; … ; 279214 124077 … 9223372036854775807 9223372036854775807; 257119 -82644 … 9223372036854775807 9223372036854775807] ≈ [-6505 48759 … 29942 -44116; -21284 -32785 … -124827 149755; … ; 98207 131677 … -159609 167192; 155563 -24042 … 113094 -127417]
```
Note all the `typemax(Int)`s that are showing up.

With a smaller matrix size:
```julia
(199 × 203) × (203 × 199): Test Failed at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:205
  Expression: blocked_mul!(C1, At', Bt') ≈ C2
   Evaluated: [63538 33754 … -29314 -3528; -58309 -11388 … 471 88377; … ; -5618 -40326 … 18126 13008; -21336 -9184 … 5516 -73428] ≈ [63538 33754 … -29314 -3528; -58309 -11388 … 471 88377; … ; -5618 -40326 … 18126 13008; -21336 -9184 … 5516 -73428]
```
Some of these didn't match, but the vast majority did.

I fixed a problem like this elsewhere recently, but for the life of me I can't yet remember what the problem was.

**Comment by DilumAluthge** [comment]
Also, what about this segfault?
```
Test Summary:                | Pass  Total
Float32 Matrix-Matrix        |   30     30

signal (11): Segmentation fault: 11
in expression starting at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:190
macro expansion at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:539 [inlined]
vstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:539 [inlined]
vstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:749 [inlined]
vstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/strided_pointers/stridedpointers.jl:161 [inlined]
vnoaliasstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:749 [inlined]
macro expansion at /Users/runner/.julia/packages/LoopVectorization/4xloY/src/reconstruct_loopset.jl:480 [inlined]
_avx_! at /Users/runner/.julia/packages/LoopVectorization/4xloY/src/reconstruct_loopset.jl:480
gemm_kernel! at /Users/runner/work/Gaius.jl/Gaius.jl/src/kernels.jl:2 [inlined]
block_mat_mat_mul! at /Users/runner/work/Gaius.jl/Gaius.jl/src/block_operations.jl:19 [inlined]
_mul! at /Users/runner/work/Gaius.jl/Gaius.jl/src/matmul.jl:107
#blocked_mul!#1 at /Users/runner/work/Gaius.jl/Gaius.jl/src/matmul.jl:39
blocked_mul! at /Users/runner/work/Gaius.jl/Gaius.jl/src/matmul.jl:35 [inlined]
macro expansion at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:205 [inlined]
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
macro expansion at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:194 [inlined]
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
top-level scope at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:191
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:834
jl_parse_eval_all at /Users/julia/buildbot/worker/package_macos64/build/src/ast.c:913
jl_load_rewrite at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:914 [inlined]
jl_load at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:919
include at ./client.jl:457
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1690 [inlined]
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:117
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:0
jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:840
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:790
jl_toplevel_eval at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:849 [inlined]
jl_toplevel_eval_in at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:883
eval at ./boot.jl:331
exec_options at ./client.jl:272
_start at ./client.jl:506
jfptr__start_57081.clone_1 at /Users/runner/hostedtoolcache/julia/1.5.3/x64/lib/julia/sys.dylib (unknown line)
true_main at /Users/runner/hostedtoolcache/julia/1.5.3/x64/bin/julia (unknown line)
main at /Users/runner/hostedtoolcache/julia/1.5.3/x64/bin/julia (unknown line)
Allocations: 357393406 (Pool: 357097716; Big: 295690); GC: 256
ERROR: Package Gaius errored during testing (received signal: 11)
Stacktrace:
 [1] pkgerror(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:52
 [2] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:1578
 [3] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:327
 [4] #test#61 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:coverage,),Tuple{Bool}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:80
 [6] top-level scope at none:1
Error: Process completed with exit code 1.
```

Log: https://github.com/MasonProtter/Gaius.jl/pull/23/checks?check_run_id=1586190359

Is that the same bug?

It seems to be happening in the test set after `Float32 Matrix-Matrix`, which is the `Int64 Matrix-Matrix` test set.

**Comment by DilumAluthge** [comment]
Also, what about this segfault?
```
Test Summary:                | Pass  Total
Float32 Matrix-Matrix        |   30     30

signal (11): Segmentation fault: 11
in expression starting at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:190
macro expansion at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:539 [inlined]
vstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:539 [inlined]
vstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:749 [inlined]
vstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/strided_pointers/stridedpointers.jl:161 [inlined]
vnoaliasstore! at /Users/runner/.julia/packages/VectorizationBase/PCwdN/src/llvm_intrin/memory_addr.jl:749 [inlined]
macro expansion at /Users/runner/.julia/packages/LoopVectorization/4xloY/src/reconstruct_loopset.jl:480 [inlined]
_avx_! at /Users/runner/.julia/packages/LoopVectorization/4xloY/src/reconstruct_loopset.jl:480
gemm_kernel! at /Users/runner/work/Gaius.jl/Gaius.jl/src/kernels.jl:2 [inlined]
block_mat_mat_mul! at /Users/runner/work/Gaius.jl/Gaius.jl/src/block_operations.jl:19 [inlined]
_mul! at /Users/runner/work/Gaius.jl/Gaius.jl/src/matmul.jl:107
#blocked_mul!#1 at /Users/runner/work/Gaius.jl/Gaius.jl/src/matmul.jl:39
blocked_mul! at /Users/runner/work/Gaius.jl/Gaius.jl/src/matmul.jl:35 [inlined]
macro expansion at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:205 [inlined]
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
macro expansion at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:194 [inlined]
macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
top-level scope at /Users/runner/work/Gaius.jl/Gaius.jl/test/runtests.jl:191
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:834
jl_parse_eval_all at /Users/julia/buildbot/worker/package_macos64/build/src/ast.c:913
jl_load_rewrite at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:914 [inlined]
jl_load at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:919
include at ./client.jl:457
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1690 [inlined]
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:117
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:0
jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:840
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:790
jl_toplevel_eval at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:849 [inlined]
jl_toplevel_eval_in at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:883
eval at ./boot.jl:331
exec_options at ./client.jl:272
_start at ./client.jl:506
jfptr__start_57081.clone_1 at /Users/runner/hostedtoolcache/julia/1.5.3/x64/lib/julia/sys.dylib (unknown line)
true_main at /Users/runner/hostedtoolcache/julia/1.5.3/x64/bin/julia (unknown line)
main at /Users/runner/hostedtoolcache/julia/1.5.3/x64/bin/julia (unknown line)
Allocations: 357393406 (Pool: 357097716; Big: 295690); GC: 256
ERROR: Package Gaius errored during testing (received signal: 11)
Stacktrace:
 [1] pkgerror(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Types.jl:52
 [2] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:1578
 [3] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:327
 [4] #test#61 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:67 [inlined]
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:coverage,),Tuple{Bool}}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:80
 [6] top-level scope at none:1
Error: Process completed with exit code 1.
```

Log: https://github.com/MasonProtter/Gaius.jl/pull/23/checks?check_run_id=1586190359

Is that the same bug?

It seems to be happening in the test set after `Float32 Matrix-Matrix`, which is the `Int64 Matrix-Matrix` test set.

**Comment by chriselrod** [comment]
I'll look into it fairly soon.

**Comment by chriselrod** [comment]
When rerun with VectorizationBase 0.14.5, tests passed on Mac: https://github.com/MasonProtter/Gaius.jl/actions/runs/434710612

**Comment by DilumAluthge** [comment]
Closing in favor of #29

**Pull request closed without merging**
