### PR TITLE
Fix covector-matrix multiplication

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request fixes covector-matrix multiplication.

### CODE REVIEW

**Review by chriselrod — DISMISSED** [review]
Yes, but I'm not that familiar with the code. Maybe it was supposed to be `size(A,2)`?

I'd double check with @MasonProtter, but as tests were passing as it is...

**Comment by DilumAluthge** [comment]
Yeah let's confirm that @MasonProtter before doing anything.

**Comment by DilumAluthge** [comment]
> but as tests were passing as it is...

I wouldn't be too reassured by that. Tests weren't covering those code paths...

**Comment by chriselrod** [comment]
> > but as tests were passing as it is...
> 
> I wouldn't be too reassured by that. Tests weren't covering those code paths...

What I meant was, deleting those paths seems fine from a correctness-perspective if a bug that prevented us from being able to hit them didn't cause test failures (although, again, I didn't look at things enough to know if maybe it should be `size(A,2)` instead of `size(A,1)`.

**Comment by MasonProtter** [comment]
Yes, it looks like what I meant to write was `size(A, 2)` there.

**Comment by MasonProtter** [comment]
It should have been essentially the transpose of the `mul(::Matrix, ::Vector)` code:
```
function _mul!(C::VecTypes{T}, A::MatTypes{T}, B::VecTypes{T}, sz) where {T<:Eltypes}
    n, k = size(A)
    if     n >= sz+8 && k >= sz+8
        block_mat_vec_mul!(C, A, B, sz)
    elseif n <  sz+8 && k >= sz+8
        block_covec_vec_mul!(C, A, B, sz)
    else
        gemm_kernel!(C, A, B)
    end
end
```

**Comment by DilumAluthge** [comment]
@MasonProtter Can you double-check that this looks correct?

**Comment by DilumAluthge** [comment]
Oh boy. It definitely is not correct.

**Comment by chriselrod** [comment]
> It should have been essentially the transpose of the `mul(::Matrix, ::Vector)` code:
> 
> ```julia
> function _mul!(C::VecTypes{T}, A::MatTypes{T}, B::VecTypes{T}, sz) where {T<:Eltypes}
>     n, k = size(A)
>     if     n >= sz+8 && k >= sz+8
>         block_mat_vec_mul!(C, A, B, sz)
>     elseif n <  sz+8 && k >= sz+8
>         block_covec_vec_mul!(C, A, B, sz)
>     else
>         gemm_kernel!(C, A, B)
>     end
> end
> ```
> 
> but I was probably careless somewhere along the way.

Should perhaps define something along the lines of
```julia
mul!(C::Covector, A::Covector, B::AbstractMatrix) = mul!(C', B', A')'
```
?

**Comment by DilumAluthge** [comment]
> Should perhaps define something along the lines of
> 
> ```julia
> mul!(C::Covector, A::Covector, B::AbstractMatrix) = mul!(C', B', A')'
> ```
> 
> ?

I tried this, but I still get weird errors.

I might need @MasonProtter's help with this one.

**Comment by DilumAluthge** [comment]
@MasonProtter Still failing :(

**Comment by MasonProtter** [comment]
Yeah, sorry I haven’t had a chance yet to delve in and see what’s wrong. Currently, we’re somehow producing a matrix where we needed to produce a covector, so that’ll need some investigation as to why.

**Comment by DilumAluthge** [comment]
https://github.com/MasonProtter/Gaius.jl/issues/79

**Pull request closed without merging**
