### PR TITLE
Transpose

### PR DESCRIPTION
**Pull request by chriselrod**
32 additions and 42 deletions, for a net of 10 fewer lines of code, adds support for transposed matrices.
```julia
julia> using Gaius, LinearAlgebra, BenchmarkTools, LoopVectorization
[ Info: Precompiling Gaius [bffe22d1-cb55-4f4e-ac2c-f4dd4bf58912]

julia> M = 1000
1000

julia> A = rand(M, M); B = rand(M, M); C1 = similar(A); C2 = similar(A);

julia> const blocked_mul! = Gaius.mul!
mul! (generic function with 3 methods)

julia> @benchmark blocked_mul!($C1, $A, $B)
BenchmarkTools.Trial:
  memory estimate:  233.30 KiB
  allocs estimate:  1851
  --------------
  minimum time:     2.340 ms (0.00% GC)
  median time:      2.823 ms (0.00% GC)
  mean time:        2.870 ms (0.87% GC)
  maximum time:     11.502 ms (76.19% GC)
  --------------
  samples:          1738
  evals/sample:     1

julia> @benchmark mul!($C2, $A, $B)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.376 ms (0.00% GC)
  median time:      2.123 ms (0.00% GC)
  mean time:        2.135 ms (0.00% GC)
  maximum time:     2.588 ms (0.00% GC)
  --------------
  samples:          2336
  evals/sample:     1

julia> C1 ≈ C2
true

julia> @benchmark blocked_mul!($C1, $A, $B')
BenchmarkTools.Trial:
  memory estimate:  233.34 KiB
  allocs estimate:  1854
  --------------
  minimum time:     2.309 ms (0.00% GC)
  median time:      2.748 ms (0.00% GC)
  mean time:        2.812 ms (0.92% GC)
  maximum time:     13.181 ms (78.75% GC)
  --------------
  samples:          1774
  evals/sample:     1

julia> @benchmark mul!($C2, $A, $B')
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.380 ms (0.00% GC)
  median time:      2.239 ms (0.00% GC)
  mean time:        2.191 ms (0.00% GC)
  maximum time:     2.468 ms (0.00% GC)
  --------------
  samples:          2276
  evals/sample:     1

julia> C1 ≈ C2
true

julia> @benchmark blocked_mul!($C1, $A', $B)
BenchmarkTools.Trial:
  memory estimate:  233.39 KiB
  allocs estimate:  1857
  --------------
  minimum time:     2.903 ms (0.00% GC)
  median time:      3.296 ms (0.00% GC)
  mean time:        3.351 ms (0.69% GC)
  maximum time:     12.269 ms (70.48% GC)
  --------------
  samples:          1490
  evals/sample:     1

julia> @benchmark mul!($C2, $A', $B)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.355 ms (0.00% GC)
  median time:      2.227 ms (0.00% GC)
  mean time:        2.152 ms (0.00% GC)
  maximum time:     2.638 ms (0.00% GC)
  --------------
  samples:          2319
  evals/sample:     1

julia> C1 ≈ C2
true

julia> @benchmark blocked_mul!($C1, $A', $B')
BenchmarkTools.Trial:
  memory estimate:  233.38 KiB
  allocs estimate:  1856
  --------------
  minimum time:     2.139 ms (0.00% GC)
  median time:      2.339 ms (0.00% GC)
  mean time:        2.394 ms (1.10% GC)
  maximum time:     13.464 ms (80.25% GC)
  --------------
  samples:          2084
  evals/sample:     1

julia> @benchmark mul!($C2, $A', $B')
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.372 ms (0.00% GC)
  median time:      2.080 ms (0.00% GC)
  mean time:        2.069 ms (0.00% GC)
  maximum time:     2.571 ms (0.00% GC)
  --------------
  samples:          2412
  evals/sample:     1

julia> C1 ≈ C2
true
```

It may be better to eventually special case `C = A' * B`.
If / when packing is added, the packing process could transpose it.

### CODE REVIEW

**Comment by chriselrod** [comment]
I've added tests for the transposed cases, although not for complex numbers.

Do you want to add support for adjoint and transposed (struct of) arrays of complex numbers?

**Comment by chriselrod** [comment]
Any idea what could be behind a test failure like [this](https://travis-ci.com/MasonProtter/Gaius.jl/jobs/292814432)?
There was a similar failure on 1.3, but it disappeared when I restarted the job without making changes.
The differences between the trailing elements of those matrices is large enough that there was definitely some problem there.

**Comment by MasonProtter** [comment]
> Do you want to add support for adjoint and transposed (struct of) arrays of complex numbers?

Yeah, that'd be a great next step. I can do it in the next few days if you don't get around to it first. 

> Any idea what could be behind a test failure like this?
> There was a similar failure on 1.3, but it disappeared when I restarted the job without making changes.
> The differences between the trailing elements of those matrices is large enough that there was definitely some problem there.

No, I've been trying to track down those strange random test failures and figure out what causes them.

Maybe one idea would be to check if the test fails and if it does, save the matrices to disk so that we can look and see if the failures are a deterministic function of the input matrices or something non-deterministic like some weird race-condition.

**Comment by MasonProtter** [comment]
I'm just going to merge this for now and get around to the AOS stuff a bit later.

**Pull request merged**
